---
dev-synthesizer-mysql:
  image: mysql:8.0.27
  container_name: dev-synthesizer-mysql
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  environment:
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_PORT: 3306
    MYSQL_DATABASE: development
    MYSQL_USER: user
    MYSQL_PASSWORD: password
  ports:
    - 3336:3306
  volumes:
    - "./mysql-data:/var/lib/mysql"
