// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// AdminUsecase is an autogenerated mock type for the AdminUsecase type
type AdminUsecase struct {
	mock.Mock
}

// NewAdminUsecase creates a new instance of AdminUsecase. It also registers a cleanup function to assert the mocks expectations.
func NewAdminUsecase(t testing.TB) *AdminUsecase {
	mock := &AdminUsecase{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
