// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/kujilabo/cocotola-synthesizer-api/pkg/service"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// RepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type RepositoryFactory struct {
	mock.Mock
}

// NewAudioRepository provides a mock function with given fields: ctx
func (_m *RepositoryFactory) NewAudioRepository(ctx context.Context) service.AudioRepository {
	ret := _m.Called(ctx)

	var r0 service.AudioRepository
	if rf, ok := ret.Get(0).(func(context.Context) service.AudioRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.AudioRepository)
		}
	}

	return r0
}

// NewRepositoryFactory creates a new instance of RepositoryFactory. It also registers a cleanup function to assert the mocks expectations.
func NewRepositoryFactory(t testing.TB) *RepositoryFactory {
	mock := &RepositoryFactory{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
